"""Add created_at to User and Review

Revision ID: 561b5be2d60b
Revises: 06b8585b9265
Create Date: 2025-09-15 22:58:38.737538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561b5be2d60b'
down_revision = '06b8585b9265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
