"""Add accuracy tracking tables

Revision ID: add_accuracy_tables
Revises: dd1b400186cb
Create Date: 2026-04-04 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_accuracy_tables'
down_revision = 'dd1b400186cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create sentiment_validation table
    op.create_table('sentiment_validation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('review_id', sa.Integer(), nullable=False),
        sa.Column('predicted_sentiment', sa.String(length=20), nullable=False),
        sa.Column('actual_sentiment', sa.String(length=20), nullable=False),
        sa.Column('is_correct', sa.Boolean(), nullable=True, server_default='0'),
        sa.Column('validated_at', sa.DateTime(), nullable=True),
        sa.Column('validated_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['review_id'], ['review.id']),
        sa.ForeignKeyConstraint(['validated_by'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create accuracy_metric table
    op.create_table('accuracy_metric',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('metric_date', sa.DateTime(), nullable=True),
        sa.Column('overall_accuracy', sa.Float(), nullable=True),
        sa.Column('positive_accuracy', sa.Float(), nullable=True),
        sa.Column('negative_accuracy', sa.Float(), nullable=True),
        sa.Column('neutral_accuracy', sa.Float(), nullable=True),
        sa.Column('total_validated', sa.Integer(), nullable=True),
        sa.Column('average_confidence', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('accuracy_metric')
    op.drop_table('sentiment_validation')
    
    # ### end Alembic commands ###
