"""Add aspect_sentiments to Review

Revision ID: dd1b400186cb
Revises: 561b5be2d60b
Create Date: 2025-09-18 21:10:08.380909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1b400186cb'
down_revision = '561b5be2d60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspect_sentiments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('aspect_sentiments')

    # ### end Alembic commands ###
